export const GET_DOCUMENTS_REQUEST = 'GET_DOCUMENTS_REQUEST';
export const GET_DOCUMENTS_FAILURE = 'GET_DOCUMENTS_FAILURE';
export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS';
export const SET_SELECTED_DOCUMENT = 'SET_SELECTED_DOCUMENT'